
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app-dp
  labels:
    app: maven-app
spec:
  replicas: 4
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  minReadySeconds: 30
  selector:
    matchLabels:
       app: maven-app
  template:
    metadata:
      name: maven-app-pod
      labels:
        app: maven-app
    spec:
      imagePullSecrets:
      - name: regcrd
      containers:
      - name: maven-app-container
        image: shraddhatilwankar/maven-app-b3643c2c0c:maven-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 800m
            memory: 1Gi
 
---

apiVersion: v1
kind: Service
metadata:
  name: maven-app-svc
spec:
  type: LoadBalancer
  selector:
    app: maven-app
  ports:
  - port: 8080
    targetPort: 8080
